### PR TITLE
JENKINS-57605 Use the "H2 API Plugin" to load H2

### PR DESCRIPTION
**Pull request by cyrille-leclerc**

### CODE REVIEW

**Comment by cyrille-leclerc** [comment]
@uhafner are you the maintainer of this plugin? I have introduced an "API plugin" to prevent version issues on h2.jar

**Comment by uhafner** [comment]
No, I'm not the maintainer. I think I just created a release so a student can finish his master theses using this plugin.

**Comment by cyrille-leclerc** [comment]
Thanks @uhafner , I think that the infos on the plugin are wrong because you are seen as the maintainer (see https://plugins.jenkins.io/database-h2 ).
Do you know how to fix this so that people don't expect you to do the maintenance of this plugin?

**Comment by uhafner** [comment]
I don't know how to fix this on the plugins index. I marked the plugin for adoption on the wiki now.

**Pull request merged**
